[package]
name = "fibonacci"
version = "0.1.0"
authors = ["Hershell A. Makowitzky <hershell.makowitzky@pn.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
